### PR TITLE
Update to FBInk 1.20.2

### PR DESCRIPTION
**Pull request by NiLuJe**
Includes a fix for a double-free in fbink_free_ot_fonts (https://github.com/NiLuJe/FBInk/pull/37) ;).

### CODE REVIEW

**Comment by NiLuJe** [comment]
And now w/ FBInk 1.20.1, hopefully with proper button_scan support on the Libra this time...

**Comment by shermp** [comment]
Thanks for this.

Once I've done some reading on the shiny new Forma that arrived today, I'll merge this.

Will also need to update KU to use this I suppose, for the Libra support

**Comment by NiLuJe** [comment]
:+1: ;).

**Comment by NiLuJe** [comment]
And now w/ 1.20.2 ;).

**Comment by shermp** [comment]
I'm gonna assume this works and merge Thank you :)

I've finally managed to get c-for-go to work, and have played around a bit with it. Seems promising, although the enums are going to require a little post processing, as they are converted to an int32 type. So either need to change the type, or tell consumers to cast to the smaller type when assigning to struct member.

If I can get c-for-go working reliably, I might see if I can add the binding to the main FBInk repo. The "new" Go modules will make that easier.

**Comment by NiLuJe** [comment]
Well, to be fair, enums are technically (usually) ints in C ;p.

**Pull request merged**
