### PR TITLE
Update to FBInk 1.19.0

### PR DESCRIPTION
**Pull request by NiLuJe**
Like the last time, `fbink_get_last_rect` isn't implemented, but the structs skeletons are there ;).

### CODE REVIEW

**Comment by shermp** [comment]
Hey, thanks for this.

From a first glance, it looks ok, but I'm not able to test atm, as I'm currently in the US on holiday.

The merge may have to wait a couple of weeks until I get home.

**Comment by NiLuJe** [comment]
No worries, enjoy your holidays ;).

**Comment by NiLuJe** [comment]
Now includes a free update to FBInk 1.18.0 ;).

**Comment by NiLuJe** [comment]
Make that 1.18.1 ;).

**Comment by shermp** [comment]
I really do need to get around to merging this don't I?

Thanks for the updates!

**Comment by NiLuJe** [comment]
And now 1.19.0... ;p.

**Comment by shermp** [comment]
Sorry, missed the email on this (due to the great 2019 DNS oopsie - err.. incident)

From a quick look, seems alright. I'm just gonna merge this as-is.

Thanks.

As an aside, I'm thinking about using https://github.com/xlab/c-for-go in the future to automate binding creation.

**Comment by NiLuJe** [comment]
Ooh, that's a tiny bit fancier than what we're using for [Lua/Python](https://github.com/koreader/ffi-cdecl) ;).

**Comment by shermp** [comment]
Yeah, I discovered it when I was looking at GUI toolkits for Go. https://github.com/golang-ui/nuklear uses it.

**Pull request merged**
