### PR TITLE
Update to FBInk 1.22.0

### PR DESCRIPTION
**Pull request by NiLuJe**
You should be used to these by now ;).

### CODE REVIEW

**Comment by shermp** [comment]
Builds ok, looks ok. No red underlines.

If you had implemented functions returning the new error codes, I would have asked for an update to `createError()`, but I'm not going to worry about that for now.

Thank you very much.

**Comment by NiLuJe** [comment]
Oh, I added 'em to the CexitCode list already, so I might as well do it ;).

**Comment by NiLuJe** [comment]
(Especially since `ReInit` *is* implemented, and can return some of those).

That said, they're not technically errors, so I'm not quite sure what to do with that...

**Comment by NiLuJe** [comment]
Reading up on https://golang.org/pkg/errors/ to grok what's happening there ;p.

**Comment by NiLuJe** [comment]
AFAIU, error (as in the Go data type) pretty much *means* error, so those definitely don't belong in `createError()`.

What would make more sense is then to have `ReInit` return the C return code, like other functions that do that kind of things with a return code (like `fbink_print` with rows).

i.e.,

```diff
diff --git a/gofbink/gofbink.go b/gofbink/gofbink.go
index b8a38b9..9028c73 100644
--- a/gofbink/gofbink.go
+++ b/gofbink/gofbink.go
@@ -697,10 +697,10 @@ func (f *FBInk) GetLastMarker() (uint32, error) {
 // ReInit handles cases where the framebuffer state such as bit depth
 // or rotation may change
 // See "fbink.h" for detailed usage and explanation
-func (f *FBInk) ReInit(cfg *FBInkConfig) error {
+func (f *FBInk) ReInit(cfg *FBInkConfig) (int, error) {
        cfgC := f.newConfigC(cfg)
        res := CexitCode(C.fbink_reinit(f.fbfd, &cfgC))
-       return createError(res)
+       return int(res), createError(res)
 }
 
 // PrintProgressBar displays a full width progress bar
```

But that's an API change... :blush:

**Comment by shermp** [comment]
Hmmm, something to think about. But yeah, if they're not errors, they shouldn't be treated as such.

As it currently stands, `createError()` would return the default case of `nil`, which is correct. One would lose those values though.

I'd be inclined to leave it as-is for now, to avoid API breakage.

**Comment by shermp** [comment]
As a side note, the error type is an interface. Basically, anything can be an error if it implements the `Error() string` method.

**Comment by shermp** [comment]
Umm, I forgot about this! Oops?

I'm gonna merge as-is, it's been long enough...

Sorry about the wait!

**Pull request merged**
