### PR TITLE
Update to FBInk 1.23.2

### PR DESCRIPTION
**Pull request by NiLuJe**
The usual ;).

### CODE REVIEW

**Comment by NiLuJe** [comment]
(Force push because I'd forgotten to disable LTO when building the lib).

**Comment by NiLuJe** [comment]
(Now 1.23.1 ;)).

**Comment by NiLuJe** [comment]
(Now 1.23.2)

**Comment by shermp** [comment]
At this point I may as well make you a maintainer of this repo eh?

EDIT: And, invite sent. You do more with this repo than I do these days.

**Comment by NiLuJe** [comment]
I still don't really do go, so I could use a quick check that nothing horribly blew up ^^.

**Comment by shermp** [comment]
Looks ok, although I'm not really setup to test at the moment.

Need to actually publish my koxtoolchain + Go docker image so I can do some automated compile + simple tests I suppose.

**Comment by NiLuJe** [comment]
Whelp, let's push the button, since I may not have time to tag 1.24 any time soon ;).

**Pull request merged**
